# Generated by Django 5.1.3 on 2024-11-09 18:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="trip",
            name="origin",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
