# Generated by Django 5.1.3 on 2024-11-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0003_alter_trip_destination_alter_trip_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="stopped_at",
            field=models.DateTimeField(null=True),
        ),
    ]
