# Generated by Django 5.1.3 on 2024-11-10 10:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0005_alter_trip_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="trip",
            name="origin",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
